mysql:
  host: localhost
  port: 3306
  database: admin_prod
  username: root
  password: Shaojian06
  timezone: +08:00
  synchronize: fasle
  logging: false
redis:
  host: localhost
  port: 6379
  password: 123456
  db: 0
jwt:
  secret: WRm0C3vkyT1KdYJdpF2D3lRcIiNtD6C721BSHe3yyxTJVH2s6jBg6OTiO23G
  expires: 2h